### PR TITLE
Add "kubectl get all" and "kubectl get elastc"

### PR DESCRIPTION
**Pull request by sakurai-youhei**
This should fulfill demands for #57. With this PR, `eck-diagnostics -r test` will bundle `elastic-system/get-all.txt`, `test/get-all.txt`, and `test/get-elastic.txt` additionally.

**Sample outputs**:

<details>
 <summary>elastic-system/get-all.txt</summary>

```
NAME                     READY   STATUS    RESTARTS       AGE   LABELS
pod/elastic-operator-0   1/1     Running   38 (15h ago)   21d   control-plane=elastic-operator,controller-revision-hash=elastic-operator-6c484b547,statefulset.kubernetes.io/pod-name=elastic-operator-0

NAME                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE   LABELS
service/elastic-webhook-server   ClusterIP   10.101.95.23   <none>        443/TCP   21d   app.kubernetes.io/version=2.6.1,control-plane=elastic-operator

NAME                                READY   AGE   LABELS
statefulset.apps/elastic-operator   1/1     21d   app.kubernetes.io/version=2.6.1,control-plane=elastic-operator
```
</details>

<details>
 <summary>test/get-all.txt</summary>

```
NAME                                 READY   STATUS             RESTARTS        AGE     LABELS
pod/db                               0/1     CrashLoopBackOff   8 (2m22s ago)   18m     run=db
pod/quickstart-es-default-0          1/1     Running            0               5h16m   common.k8s.elastic.co/type=elasticsearch,controller-revision-hash=quickstart-es-default-56fb7fc44c,elasticsearch.k8s.elastic.co/cluster-name=quickstart,elasticsearch.k8s.elastic.co/http-scheme=https,elasticsearch.k8s.elastic.co/node-data=true,elasticsearch.k8s.elastic.co/node-data_cold=true,elasticsearch.k8s.elastic.co/node-data_content=true,elasticsearch.k8s.elastic.co/node-data_frozen=true,elasticsearch.k8s.elastic.co/node-data_hot=true,elasticsearch.k8s.elastic.co/node-data_warm=true,elasticsearch.k8s.elastic.co/node-ingest=true,elasticsearch.k8s.elastic.co/node-master=true,elasticsearch.k8s.elastic.co/node-ml=true,elasticsearch.k8s.elastic.co/node-remote_cluster_client=true,elasticsearch.k8s.elastic.co/node-transform=true,elasticsearch.k8s.elastic.co/node-voting_only=false,elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default,elasticsearch.k8s.elastic.co/version=7.12.0,statefulset.kubernetes.io/pod-name=quickstart-es-default-0
pod/quickstart-kb-56c4d6f74c-jplwl   1/1     Running            0               5h16m   common.k8s.elastic.co/type=kibana,kibana.k8s.elastic.co/name=quickstart,kibana.k8s.elastic.co/version=7.12.0,pod-template-hash=56c4d6f74c

NAME                                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE     LABELS
service/quickstart-es-default         ClusterIP   None           <none>        9200/TCP   5h16m   common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart,elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default
service/quickstart-es-http            ClusterIP   10.97.108.16   <none>        9200/TCP   5h16m   common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart
service/quickstart-es-internal-http   ClusterIP   10.96.99.249   <none>        9200/TCP   5h16m   common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart
service/quickstart-es-transport       ClusterIP   None           <none>        9300/TCP   5h16m   common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart
service/quickstart-kb-http            ClusterIP   10.97.37.144   <none>        5601/TCP   5h16m   common.k8s.elastic.co/type=kibana,kibana.k8s.elastic.co/name=quickstart

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
deployment.apps/quickstart-kb   1/1     1            1           5h16m   common.k8s.elastic.co/template-hash=2844961182,common.k8s.elastic.co/type=kibana,kibana.k8s.elastic.co/name=quickstart

NAME                                       DESIRED   CURRENT   READY   AGE     LABELS
replicaset.apps/quickstart-kb-56c4d6f74c   1         1         1       5h16m   common.k8s.elastic.co/type=kibana,kibana.k8s.elastic.co/name=quickstart,kibana.k8s.elastic.co/version=7.12.0,pod-template-hash=56c4d6f74c

NAME                                     READY   AGE     LABELS
statefulset.apps/quickstart-es-default   1/1     5h16m   common.k8s.elastic.co/template-hash=3837151210,common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart,elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default
```
</details>

<details>
 <summary>test/get-elastic.txt</summary>

```
NAME                                                    HEALTH   NODES   VERSION   PHASE   AGE     LABELS
elasticsearch.elasticsearch.k8s.elastic.co/quickstart   green    1       7.12.0    Ready   5h16m   <none>

NAME                                      HEALTH   NODES   VERSION   AGE     LABELS
kibana.kibana.k8s.elastic.co/quickstart   green    1       7.12.0    5h16m   <none>
```
</details>

If you add `--filters elasticsearch=quickstart,kibana=quickstart` to the command, it filters out unrelated resources such as `pod/db` from the above `test/get-all.txt`.

### CODE REVIEW

**Comment by sakurai-youhei** [comment]
I find that `kubectl get all` command collects broader information than README mentions.

With kubectl 1.26.0+, `kubectl api-resources -o wide` shows CATEGORIES columns (thanks to https://github.com/kubernetes/kubectl/commit/7c5e877c4dfe08ca18cd25889c6c988e2d298d07), which tells what resources are categorized to `all`.

```shell
$ kubectl api-resources -o wide | grep all
pods                              po           v1                                          true         Pod                              create,delete,deletecollection,get,list,patch,update,watch   all
replicationcontrollers            rc           v1                                          true         ReplicationController            create,delete,deletecollection,get,list,patch,update,watch   all
services                          svc          v1                                          true         Service                          create,delete,deletecollection,get,list,patch,update,watch   all
daemonsets                        ds           apps/v1                                     true         DaemonSet                        create,delete,deletecollection,get,list,patch,update,watch   all
deployments                       deploy       apps/v1                                     true         Deployment                       create,delete,deletecollection,get,list,patch,update,watch   all
replicasets                       rs           apps/v1                                     true         ReplicaSet                       create,delete,deletecollection,get,list,patch,update,watch   all
statefulsets                      sts          apps/v1                                     true         StatefulSet                      create,delete,deletecollection,get,list,patch,update,watch   all
horizontalpodautoscalers          hpa          autoscaling/v2                              true         HorizontalPodAutoscaler          create,delete,deletecollection,get,list,patch,update,watch   all
cronjobs                          cj           batch/v1                                    true         CronJob                          create,delete,deletecollection,get,list,patch,update,watch   all
jobs                                           batch/v1                                    true         Job                              create,delete,deletecollection,get,list,patch,update,watch   all

$ kubectl version -o yaml | grep Version
clientVersion:
  gitVersion: v1.26.3
  goVersion: go1.19.7
kustomizeVersion: v4.5.7
serverVersion:
  gitVersion: v1.25.4
  goVersion: go1.19.3
```

https://github.com/elastic/eck-diagnostics/blob/9e8588345ccb1ba4d18281f8a816207c1446e060/README.md?plain=1#L57-L66

https://github.com/elastic/eck-diagnostics/blob/9e8588345ccb1ba4d18281f8a816207c1446e060/README.md?plain=1#L68-L75

So, I think I also need to update README accordingly.

**Comment by sakurai-youhei** [comment]
README is updated.

So now, if you put `--filters elasticsearch=quickstart,kibana=quickstart` to the command, it filters out unmatched resources from all `get-all.txt`, which allows users to limit the scope of resources collection.

**Comment by thbkrkr** [comment]
We are quite reluctant to make this enhancement because:
- users have already complained about the size of the diagnosis and it adds files when the data is already present in the diagnosis even if it's small files
- apply the filters to the `get` commands seems a bit hacky

Wouldn't it be better to put our efforts into a diagnostic visualization tool?

**Comment by sakurai-youhei** [comment]
@thbkrkr Could you give a review before this PR gets stale somewhen? Thanks!

**Comment by thbkrkr** [comment]
Closing to focus efforts on a diagnostic visualization tool as mentioned in https://github.com/elastic/eck-diagnostics/issues/57.

**Pull request closed without merging**
