### PR TITLE
Adding new param stack-diagnostics-timeout 

### LINKED ISSUE #78: Make the stack diagnostic timeout configurable
Currently the timeout is hard-coded and in certain environments the 5 minute limit might not be enough. We should make this an additional parameter `stack-diagnostics-timeout` with a default of 5 minutes which would allow users to adjust this as needed.

### PR DESCRIPTION
**Pull request by framsouza**
Fix #78

### CODE REVIEW

**Comment by framsouza** [comment]
ok to test

**Comment by framsouza** [comment]
jenkins test this please

**Comment by framsouza** [comment]
cla/check

**Comment by framsouza** [comment]
cla/check

**Comment by framsouza** [comment]
cla/check

**Comment by framsouza** [comment]
cla/check

**Comment by thbkrkr** [comment]
I'm tempted to also make this timeout applicable for the elastic-agent diagnostic, which was recently added (#97). What do you think?

**Comment by pebrc** [comment]
> I'm tempted to also make this timeout applicable for the elastic-agent diagnostic, which was recently added (https://github.com/elastic/eck-diagnostics/pull/97). What do you think?

I think that's a bit tricky as the agent diagnostics work differently. It is basically just a `kubectl exec` command. We can of course look into whether that command is somehow cancellable, my first impression is that that's non-obvious. So probably takes a bit of digging.  I therefore think it would be ok to do that in a follow up task.

**Review by pebrc — APPROVED** [review]
LGTM let's tackle the Agent timeout seperately

**Pull request merged**
